routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Controller@main')->name('root');
Route::get('/content-change-manager', 'Controller@manager')->name('manager');
Route::resource('main-bags', 'MainBagController');
Route::resource('features', 'MainBagFeatureController');
Route::resource('bag-colors', 'BagColorsController');
Route::resource('chechol-colors', 'ChecholColorsController');
Route::resource('pictures', 'PicturesController');

resources/views/layouts/layout.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>
    <style>
        body {
            vertical-align: top;
            text-align: center;

        }
        body tr td, body tr th {
            padding: 10px;
        }
    </style>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

</head>
<body>
<div class="flex-center position-ref full-height">
    <ul style="position: absolute; width: 100px; height: 100%; right: 0; border-left: 2px solid">
        <h5>Меню</h5>
        <br>
        <li><a href="{{route('root')}}">Сайт</a> </li>
        <li><a href="{{route('main-bags.index')}}">Реклама чемоданов</a> </li>
        <li><a href="{{route('features.index')}}">Преимущества чемоданов</a> </li>
        <li><a href="{{route('bag-colors.index')}}">Каталог чемоданов</a> </li>
        <li><a href="{{route('chechol-colors.index')}}">Каталог чехлов</a> </li>
        <li><a href="{{route('pictures.index')}}">Изображения</a> </li>
    </ul>
    <div class="content">
        @yield('content')
    </div>
</div>
</body>
</html>

resources/views/layouts/shop.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="format-detection" content="telephone=no">
        <title>Онлайн-магазин ЧЕМОДАН.CLUB</title>
        <meta name="description"
              content="Недорогие, дешевые чемоданы на колесах в интернет магазине, Быстрая доставка в Москве! Доставка в течение 2-3 часов!">
        <meta name="keywords"
              content="чемодан на колесах, чемоданы на колесах недорого, недорогие чемоданы на колесах, чемоданы на колесах в Москве, чемоданы на колесах магазин, чемодан на колесах интернет, чемодан на колесах интернет магазин, чемодан колесах магазин недорого, чемодан на колесах интернет магазин недорого , недорогие чемоданы на колесах интернет магазин">
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        @yield('assets')
        @include('layouts.yandex')
    </head>
    <body>
    @yield('body')
    </body>
</html>

resources/views/layouts/yandex.blade.php
<!— Yandex.Metrika counter —>
<script type="text/javascript" >
    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

    ym(51522779, "init", {
        id:51522779,
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
    });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/51522779" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!— /Yandex.Metrika counter —>